"""
SEBI Configuration Module
"""

from .sebi_comprehensive_prompts import (
    SEBI_SYSTEM_INSTRUCTIONS,
    SEBI_INTENT_CLASSIFICATION_PROMPT,
    SEBI_ENTITY_EXTRACTION_PROMPT,
    SEBI_RESPONSE_GENERATION_PROMPT,
    SEBI_NIL_DATA_RESPONSE_PROMPT
)

__all__ = [
    'SEBI_SYSTEM_INSTRUCTIONS',
    'SEBI_INTENT_CLASSIFICATION_PROMPT',
    'SEBI_ENTITY_EXTRACTION_PROMPT',
    'SEBI_RESPONSE_GENERATION_PROMPT',
    'SEBI_NIL_DATA_RESPONSE_PROMPT'
]