"""
Configuration Modules Package
Provides separate configuration for BSE, SEBI, and RBI databases
"""

from .bse import (
    BSE_SYSTEM_INSTRUCTIONS,
    BSE_INTENT_CLASSIFICATION_PROMPT,
    BSE_ENTITY_EXTRACTION_PROMPT,
    BSE_RESPONSE_GENERATION_PROMPT,
    BSE_RD_INNOVATION_PROMPT,
    BSE_NIL_DATA_RESPONSE_PROMPT
)

from .sebi import (
    SEBI_SYSTEM_INSTRUCTIONS,
    SEBI_INTENT_CLASSIFICATION_PROMPT,
    SEBI_ENTITY_EXTRACTION_PROMPT,
    SEBI_RESPONSE_GENERATION_PROMPT,
    SEBI_NIL_DATA_RESPONSE_PROMPT
)

from .rbi import (
    RBI_SYSTEM_INSTRUCTIONS,
    RBI_INTENT_CLASSIFICATION_PROMPT,
    RBI_ENTITY_EXTRACTION_PROMPT,
    RBI_RESPONSE_GENERATION_PROMPT,
    RBI_NIL_DATA_RESPONSE_PROMPT
)

from .config_manager import ConfigManager, get_config_manager

__all__ = [
    # BSE Configurations
    'BSE_SYSTEM_INSTRUCTIONS',
    'BSE_INTENT_CLASSIFICATION_PROMPT',
    'BSE_ENTITY_EXTRACTION_PROMPT',
    'BSE_RESPONSE_GENERATION_PROMPT',
    'BSE_RD_INNOVATION_PROMPT',
    'BSE_NIL_DATA_RESPONSE_PROMPT',
    
    # SEBI Configurations
    'SEBI_SYSTEM_INSTRUCTIONS',
    'SEBI_INTENT_CLASSIFICATION_PROMPT',
    'SEBI_ENTITY_EXTRACTION_PROMPT',
    'SEBI_RESPONSE_GENERATION_PROMPT',
    'SEBI_NIL_DATA_RESPONSE_PROMPT',
    
    # RBI Configurations
    'RBI_SYSTEM_INSTRUCTIONS',
    'RBI_INTENT_CLASSIFICATION_PROMPT',
    'RBI_ENTITY_EXTRACTION_PROMPT',
    'RBI_RESPONSE_GENERATION_PROMPT',
    'RBI_NIL_DATA_RESPONSE_PROMPT',
    
    # Configuration Manager
    'ConfigManager',
    'get_config_manager'
]