"""
BSE Configuration Module
"""

from .bse_comprehensive_prompts import (
    BSE_SYSTEM_INSTRUCTIONS,
    BSE_INTENT_CLASSIFICATION_PROMPT,
    BSE_ENTITY_EXTRACTION_PROMPT,
    BSE_RESPONSE_GENERATION_PROMPT,
    BSE_RD_INNOVATION_PROMPT,
    BSE_NIL_DATA_RESPONSE_PROMPT
)

__all__ = [
    'BSE_SYSTEM_INSTRUCTIONS',
    'BSE_INTENT_CLASSIFICATION_PROMPT',
    'BSE_ENTITY_EXTRACTION_PROMPT',
    'BSE_RESPONSE_GENERATION_PROMPT',
    'BSE_RD_INNOVATION_PROMPT',
    'BSE_NIL_DATA_RESPONSE_PROMPT'
]