"""
RBI Configuration Module
"""

from .rbi_comprehensive_prompts import (
    RBI_SYSTEM_INSTRUCTIONS,
    RBI_INTENT_CLASSIFICATION_PROMPT,
    RBI_ENTITY_EXTRACTION_PROMPT,
    RBI_RESPONSE_GENERATION_PROMPT,
    RBI_NIL_DATA_RESPONSE_PROMPT
)

__all__ = [
    'RBI_SYSTEM_INSTRUCTIONS',
    'RBI_INTENT_CLASSIFICATION_PROMPT',
    'RBI_ENTITY_EXTRACTION_PROMPT',
    'RBI_RESPONSE_GENERATION_PROMPT',
    'RBI_NIL_DATA_RESPONSE_PROMPT'
]